// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"RR_Pixi8Particles","status":true,"description":"RPG Reactor / PixiJS 8 native Particle demo","parameters":{}}
];
